on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Resume and Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: make test
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
      - name: Create Release with Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/ScottJohnson.md,output/ScottJohnson.pdf,output/ScottJohnson.html"
          tag: "latest"
