on: push

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Resume
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y pandoc lmodern wkhtmltopdf
      - run: make test
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/
      - name: Copy markdown resume to remote host
        uses: garygrossgarten/github-action-scp@release
        with:
          local: output/ScottJohnson.md
          remote: /var/www/www.jwir3.com/resume/resume.md
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USERNAME }}
          privateKey: ${{ secrets.UPLOAD_PRIVATE_KEY}}
      - name: Copy pdf resume to remote host
        uses: garygrossgarten/github-action-scp@release
        with:
          local: output/ScottJohnson.pdf
          remote: /var/www/www.jwir3.com/resume/resume.pdf
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USERNAME }}
          privateKey: ${{ secrets.UPLOAD_PRIVATE_KEY}}
      - name: Copy html resume to remote host
        uses: garygrossgarten/github-action-scp@release
        with:
          local: output/ScottJohnson.html
          remote: /var/www/www.jwir3.com/resume/resume.html
          host: ${{ secrets.UPLOAD_HOST }}
          username: ${{ secrets.UPLOAD_USERNAME }}
          privateKey: ${{ secrets.UPLOAD_PRIVATE_KEY}}
